In [1]:
import pandas as pd

data = {
    "recipe": ["Veg Omelette", "Paneer Butter Masala", "Chicken Stir Fry"],
    "meal": ["breakfast", "lunch", "dinner"],
    "difficulty": ["easy", "medium", "easy"],
    "type": ["healthy", "indulgent", "healthy"]
}

df = pd.DataFrame(data)
df

                 recipe       meal difficulty       type
0          Veg Omelette  breakfast       easy    healthy
1  Paneer Butter Masala      lunch     medium  indulgent
2      Chicken Stir Fry     dinner       easy    healthy

In [2]:
pantry = pd.read_csv(r"C:\Users\Eshwari Anand Naidu\Desktop\COMPUTER SCIENCE\smartpantry\data\pantry.csv")
pantry

  ingredient  quantity unit
0       eggs         6  pcs
1      onion       500    g
2       milk      1000   ml
3     paneer       200    g
4        oil       250   ml